config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flats#index"
  resources :flats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1>All our Flats</h1>
  <p>All <%= @flats.count %> flats.</p>
  <div class=" row mt-4 w-100 mx-0 ">
    <% @flats.each do |flat| %>
      <div class="col-4 mb-3 px-3">
          <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title"><%= flat.name %></h5>
              <p class="card-text"><%= flat.address %></p>
              <div class="d-flex ">
                <div class="d-flex ms-3">
                  <i class="fa-solid fa-user-group"></i>
                  <p><%= flat.number_of_guests %></p>
                </div>
                <div class="d-flex ms-3">
                  <i class="fa-solid fa-euro-sign"></i>
                  <p><%= flat.price_per_night %></p>
                </div>
              </div>
              <div class="d-flex justify-content-between ">
                <a href=""><%= link_to 'More info', flat_path(flat) %></a>
                <a href=""><%= link_to 'More info', flat_path(flat) %></a>
                <a href=""><%= link_to 'More info', flat_path(flat) %></a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Simple Airbnb</a>
    <div class="d-flex">
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success me-2" type="submit">Search</button>
      </form>
        <button class="btn btn-outline-primary" type="submit">Add Flat</button>
    </div>
  </div>
</nav>